spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    #password:
    # 最大等待时间，超时则抛出异常，否则请求一直等待
    timeout: 3000ms
    lettuce:
      pool:
        # 最大连接数，负值表示没有限制，默认8
        max-active: 20
        # 最大阻塞等待时间，负值表示没限制，默认-1
        max-wait: -1
        # 最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接，默认0
        min-idle: 0

# 腾讯云短信
tencentcloud:
  sms:
    secret-id: 你的keyid
    secret-key: 你的keysecret
    endpoint-domain: sms.ap-guangzhou.tencentcloudapi.com
    region: ap-guangzhou
    sdk-app-id: 你的短信应用ID
    sign-name: 你的短信签名模板
    template-id: 你的正文模板ID

logging:
  level:
    # 以什么级别监控哪个接口
    xyz.raysmen.lp.sms.client.CoreUserInfoClient: DEBUG